_wandb:
    value:
        cli_version: 0.19.8
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": avg_val_loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": val_loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": train_loss_step
              "5": 1
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 49
                - 53
                - 55
                - 103
            "2":
                - 1
                - 5
                - 9
                - 11
                - 49
                - 53
                - 55
                - 103
            "3":
                - 2
                - 7
                - 13
                - 23
                - 55
                - 66
            "4": 3.11.11
            "5": 0.19.8
            "6": 4.49.0
            "8":
                - 1
                - 5
            "12": 0.19.8
            "13": linux-x86_64
