_wandb:
    value:
        cli_version: 0.19.8
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": train_loss_step
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": val_loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": val_acc
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": val_cohen_kappa
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": train_loss_epoch
              "5": 1
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 35
                - 49
                - 53
                - 55
                - 103
            "2":
                - 1
                - 5
                - 9
                - 11
                - 35
                - 49
                - 53
                - 55
                - 103
            "3":
                - 2
                - 7
                - 13
                - 23
                - 55
                - 66
            "4": 3.11.11
            "5": 0.19.8
            "6": 4.49.0
            "8":
                - 1
                - 5
            "12": 0.19.8
            "13": linux-x86_64
cnn_output_channels:
    value: 32
debug:
    value: false
dropout:
    value: 0.2280836563350801
label_smoothing:
    value: 0.08688433073858796
lr:
    value: 0.0005318141131023286
lstm_hidden_size:
    value: 64
lstm_layers:
    value: 6
non_acc_dim:
    value: 5
num_sleep_stages:
    value: 5
weight_tensor:
    value: tensor([0.8861, 1.8893, 0.3833, 5.8883, 1.7758])
