_wandb:
    value:
        cli_version: 0.19.8
        m:
            - "1": val_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": Predicted Label Distribution_table._latest_artifact_path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Predicted Label Distribution_table.path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Predicted Label Distribution_table._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Predicted Label Distribution_table.size
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": True Label Distribution_table.path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": True Label Distribution_table.ncols
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": True Label Distribution_table.nrows
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Predicted Label Distribution_table.sha256
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": True Label Distribution_table.sha256
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": True Label Distribution_table.size
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": True Label Distribution_table.artifact_path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Predicted Label Distribution_table.artifact_path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Predicted Label Distribution_table.nrows
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_loss_epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Predicted Label Distribution_table.ncols
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_loss_step
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": True Label Distribution_table._latest_artifact_path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": True Label Distribution_table._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_cohen_kappa
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 35
                - 49
                - 53
                - 55
                - 103
            "2":
                - 1
                - 5
                - 9
                - 11
                - 35
                - 49
                - 53
                - 55
                - 103
            "3":
                - 2
                - 7
                - 13
                - 23
                - 55
                - 61
                - 66
            "4": 3.11.11
            "5": 0.19.8
            "6": 4.49.0
            "8":
                - 1
                - 5
            "12": 0.19.8
            "13": linux-x86_64
        visualize:
            Predicted Label Distribution:
                panel_config:
                    fieldSettings:
                        label: Class
                        value: Count
                    panelDefId: wandb/bar/v0
                    stringSettings:
                        title: Predicted Label Distribution
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: Predicted Label Distribution_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            True Label Distribution:
                panel_config:
                    fieldSettings:
                        label: Class
                        value: Count
                    panelDefId: wandb/bar/v0
                    stringSettings:
                        title: True Label Distribution
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: True Label Distribution_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
class_weights:
    value: '[0.85966223 1.89339284 0.38728564 6.01506629 1.78483053]'
cnn_output_channels:
    value: 16
in_channels:
    value: 6
learning_rate:
    value: 0.0001
lstm_hidden_size:
    value: 64
num_layers:
    value: 2
num_sleep_stages:
    value: 5
