_wandb:
    value:
        cli_version: 0.19.8
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 35
                - 49
                - 53
                - 55
                - 103
            "2":
                - 1
                - 5
                - 9
                - 11
                - 35
                - 49
                - 53
                - 55
                - 103
            "3":
                - 7
                - 13
                - 23
                - 55
                - 66
            "4": 3.11.11
            "5": 0.19.8
            "6": 4.49.0
            "8":
                - 1
                - 5
            "12": 0.19.8
            "13": linux-x86_64
cnn_output_channels:
    value: 32
debug:
    value: false
lr:
    value: 0.0003765617930403359
lstm_hidden_size:
    value: 128
lstm_layers:
    value: 2
non_acc_dim:
    value: 5
num_sleep_stages:
    value: 5
weight_tensor:
    value: tensor([0.8991, 1.7763, 0.3777, 6.7136, 1.8941])
