_wandb:
    value:
        cli_version: 0.19.8
        m:
            - "1": train_loss_step
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_loss_epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 49
                - 53
                - 55
                - 103
            "2":
                - 1
                - 5
                - 9
                - 11
                - 49
                - 53
                - 55
                - 103
            "3":
                - 2
                - 7
                - 13
                - 23
                - 55
                - 66
            "4": 3.11.11
            "5": 0.19.8
            "6": 4.49.0
            "8":
                - 1
                - 5
            "12": 0.19.8
            "13": linux-x86_64
d_ff:
    value: 256
d_model:
    value: 128
dropout:
    value: 0.1
input_dim:
    value: 5
lr:
    value: 0.001
max_length:
    value: 7817
num_classes:
    value: 5
num_dec_layers:
    value: 2
num_enc_layers:
    value: 2
num_heads:
    value: 4
