_wandb:
    value:
        cli_version: 0.19.8
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 49
                - 53
                - 55
                - 103
            "2":
                - 1
                - 5
                - 9
                - 11
                - 49
                - 53
                - 55
                - 103
            "3":
                - 2
                - 7
                - 23
                - 55
                - 66
            "4": 3.11.11
            "5": 0.19.8
            "6": 4.49.0
            "8":
                - 1
                - 5
            "12": 0.19.8
            "13": linux-x86_64
class_weights:
    value: '[0.82251347 5.00621272 0.49379841 1.78780618]'
cnn_output_channels:
    value: 32
in_channels:
    value: 6
learning_rate:
    value: 0.001
lstm_hidden_size:
    value: 128
num_layers:
    value: 2
num_sleep_stages:
    value: 5
