_wandb:
    value:
        cli_version: 0.19.8
        m:
            - "1": epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": val_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_acc
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_cohen_kappa
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_loss_epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_loss_step
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 49
                - 53
                - 55
                - 103
            "2":
                - 1
                - 5
                - 9
                - 11
                - 49
                - 53
                - 55
                - 103
            "3":
                - 2
                - 7
                - 13
                - 23
                - 55
                - 66
            "4": 3.11.11
            "5": 0.19.8
            "6": 4.49.0
            "8":
                - 1
                - 5
            "12": 0.19.8
            "13": linux-x86_64
cnn_hidden_channels:
    value: 32
cnn_output_channels:
    value: 64
convnet:
    value: CNN
debug:
    value: false
dropout:
    value: 0.2
hf_input_channels:
    value: 4
learning_rate:
    value: 0.001
lf_input_channels:
    value: 5
lstm_bidirectional:
    value: true
lstm_hidden_size:
    value: 128
lstm_num_layers:
    value: 2
num_sleep_stages:
    value: 5
weight_decay:
    value: 5e-05
weight_tensor:
    value: tensor([0.9495, 1.9399, 0.3718, 5.4775, 1.7882])
